grails-app/domain/com/osem/Permanent.groovy
package com.osem

import java.util.Date;

class Permanent {
	
    static belongsTo = [person:Person]
    Date permDate
    String permNotes
    Date createDate

    static constraints = {
    }
    
    static mapping = {
        person index:true
    }
}

grails-app/controllers/com/osem/PermanentController.groovy
package com.osem



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_HR'])
@Transactional(readOnly = true)
class PermanentController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Permanent.list(params), model:[permanentInstanceCount: Permanent.count()]
    }

    def show(Permanent permanentInstance) {
        respond permanentInstance
    }

    def create() {
        respond new Permanent(params)
    }

    @Transactional
    def save(Permanent permanentInstance) {
        if (permanentInstance == null) {
            notFound()
            return
        }

        if (permanentInstance.hasErrors()) {
            respond permanentInstance.errors, view:'create'
            return
        }

        permanentInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'permanent.label', default: 'Permanent'), permanentInstance.id])
                redirect permanentInstance
            }
            '*' { respond permanentInstance, [status: CREATED] }
        }
    }

    def edit(Permanent permanentInstance) {
        respond permanentInstance
    }

    @Transactional
    def update(Permanent permanentInstance) {
        if (permanentInstance == null) {
            notFound()
            return
        }

        if (permanentInstance.hasErrors()) {
            respond permanentInstance.errors, view:'edit'
            return
        }

        permanentInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Permanent.label', default: 'Permanent'), permanentInstance.id])
                redirect permanentInstance
            }
            '*'{ respond permanentInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Permanent permanentInstance) {

        if (permanentInstance == null) {
            notFound()
            return
        }

        permanentInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Permanent.label', default: 'Permanent'), permanentInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'permanent.label', default: 'Permanent'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/permanent/_form.gsp
<%@ page import="com.osem.Permanent" %>



<div class="form-group fieldcontain ${hasErrors(bean: permanentInstance, field: 'createDate', 'error')} ">
	<label class="col-lg-2 control-label" for="createDate">
		<g:message code="permanent.createDate.label" default="Create Date" />
		
	</label>
	<div class="col-lg-10"><g:datePicker class="form-control" name="createDate" precision="day" value="${permanentInstance?.createDate}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: permanentInstance, field: 'permDate', 'error')} ">
	<label class="col-lg-2 control-label" for="permDate">
		<g:message code="permanent.permDate.label" default="Perm Date" />
		
	</label>
	<div class="col-lg-10"><g:datePicker class="form-control" name="permDate" precision="day" value="${permanentInstance?.permDate}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: permanentInstance, field: 'permNotes', 'error')} ">
	<label class="col-lg-2 control-label" for="permNotes">
		<g:message code="permanent.permNotes.label" default="Perm Notes" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="permNotes" value="${permanentInstance?.permNotes}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: permanentInstance, field: 'person', 'error')} ">
	<label class="col-lg-2 control-label" for="person">
		<g:message code="permanent.person.label" default="Person" />
		
	</label>
	<div class="col-lg-10"><g:select class="form-control" id="person" name="person.id" from="${com.osem.Person.list()}" optionKey="id" required="" value="${permanentInstance?.person?.id}"/></div>

</div>

grails-app/views/permanent/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'permanent.label', default: 'Permanent')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.create.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${permanentInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${permanentInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:permanentInstance, action:'save']"
							class="form-horizontal"
							>
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:submitButton name="create" class="btn btn-primary"
									value="${message(code: 'default.button.create.label', default: 'Create')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/permanent/edit.gsp
<%@ page import="com.osem.Permanent" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'permanent.label', default: 'Permanent')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.edit.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${permanentInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${permanentInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:permanentInstance, action:'update']"
							method="PUT" class="form-horizontal"
							>
							<g:hiddenField name="version"
								value="${permanentInstance?.version}" />
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:actionSubmit class="btn btn-primary" action="update"
									value="${message(code: 'default.button.update.label', default: 'Update')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/permanent/index.gsp
<%@ page import="com.osem.Permanent" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'permanent.label', default: 'Permanent')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.list.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="bootstrap-admin-panel-content">
						<g:if test="${permanentInstanceList}">
							<table class="table bootstrap-admin-table-with-actions">
								<thead>
									<tr>
										
						<g:sortableColumn property="createDate" title="${message(code: 'permanent.createDate.label', default: 'Create Date')}" />
					
						<g:sortableColumn property="permDate" title="${message(code: 'permanent.permDate.label', default: 'Perm Date')}" />
					
						<g:sortableColumn property="permNotes" title="${message(code: 'permanent.permNotes.label', default: 'Perm Notes')}" />
					
						<th><g:message code="permanent.person.label" default="Person" /></th>
					
									</tr>
								</thead>
								<tbody>
									<g:each in="${permanentInstanceList}" status="i"
										var="permanentInstance">
										<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
											
						<td><g:link action="show" id="${permanentInstance.id}">${fieldValue(bean: permanentInstance, field: "createDate")}</g:link></td>
					
						<td><g:formatDate date="${permanentInstance.permDate}" /></td>
					
						<td>${fieldValue(bean: permanentInstance, field: "permNotes")}</td>
					
						<td>${fieldValue(bean: permanentInstance, field: "person")}</td>
					
										</tr>
									</g:each>
								</tbody>
							</table>
							<div class="pagination">
								<g:paginate total="${permanentInstanceCount ?: 0}" />
							</div>
						</g:if>
						<g:else>
							No permanent found
						</g:else>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/permanent/show.gsp
<%@ page import="com.osem.Permanent" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'permanent.label', default: 'Permanent')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.show.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${permanentInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${permanentInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<dl class="dl-horizontal">
							
				<g:if test="${permanentInstance?.createDate}">
					<dt><g:message code="permanent.createDate.label" default="Create Date" /></dt>
					
						<dd><g:formatDate date="${permanentInstance?.createDate}" /></dd>
					
				</g:if>
			
				<g:if test="${permanentInstance?.permDate}">
					<dt><g:message code="permanent.permDate.label" default="Perm Date" /></dt>
					
						<dd><g:formatDate date="${permanentInstance?.permDate}" /></dd>
					
				</g:if>
			
				<g:if test="${permanentInstance?.permNotes}">
					<dt><g:message code="permanent.permNotes.label" default="Perm Notes" /></dt>
					
						<dd><g:fieldValue bean="${permanentInstance}" field="permNotes"/></dd>
					
				</g:if>
			
				<g:if test="${permanentInstance?.person}">
					<dt><g:message code="permanent.person.label" default="Person" /></dt>
					
						<dd><g:link controller="person" action="show" id="${permanentInstance?.person?.id}">${permanentInstance?.person?.encodeAsHTML()}</g:link></dd>
					
				</g:if>
			
						</dl>
						<g:form url="[resource:permanentInstance, action:'delete']"
							method="DELETE">
							<fieldset class="buttons">
								<g:link class="btn btn-primary" action="edit"
									resource="${permanentInstance}">
									<g:message code="default.button.edit.label" default="Edit" />
								</g:link>
								<g:actionSubmit class="btn btn-default" action="delete"
									value="${message(code: 'default.button.delete.label', default: 'Delete')}"
									onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>