grails-app/domain/com/osem/Education.groovy
package com.osem

class Education {

    static belongsTo = [person:Person]
    String eduLevel
    String institution
    Integer yearIn
    Integer yearOut
    String faculty
    String majors
    String title

    static constraints = {
        eduLevel inList:['SD','SMP','SMU','D1','D3','S1','S2','S3']
        faculty nullable:true
        majors nullable:true
        title nullable:true
    }
    
    static mapping = {
        person index:true
    }
	
    String toString() {
        institution
    }
}

grails-app/controllers/com/osem/EducationController.groovy
package com.osem



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_HR'])
@Transactional(readOnly = true)
class EducationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Education.list(params), model:[educationInstanceCount: Education.count()]
    }

    def show(Education educationInstance) {
        respond educationInstance
    }

    def create() {
        respond new Education(params)
    }

    @Transactional
    def save(Education educationInstance) {
        if (educationInstance == null) {
            notFound()
            return
        }

        if (educationInstance.hasErrors()) {
            respond educationInstance.errors, view:'create'
            return
        }

        educationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'education.label', default: 'Education'), educationInstance.id])
                redirect controller:"person",action:"show",id:educationInstance.person.id
            }
            '*' { respond educationInstance, [status: CREATED] }
        }
    }

    def edit(Education educationInstance) {
        respond educationInstance
    }

    @Transactional
    def update(Education educationInstance) {
        if (educationInstance == null) {
            notFound()
            return
        }

        if (educationInstance.hasErrors()) {
            respond educationInstance.errors, view:'edit'
            return
        }

        educationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Education.label', default: 'Education'), educationInstance.id])
                redirect educationInstance
            }
            '*'{ respond educationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Education educationInstance) {

        if (educationInstance == null) {
            notFound()
            return
        }

        educationInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Education.label', default: 'Education'), educationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'education.label', default: 'Education'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/education/_form.gsp
<%@ page import="com.osem.Education" %>



<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'eduLevel', 'error')} ">
	<label class="col-lg-2 control-label" for="eduLevel">
		<g:message code="education.eduLevel.label" default="Jenjang" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="eduLevel" value="${educationInstance?.eduLevel}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'institution', 'error')} ">
	<label class="col-lg-2 control-label" for="institution">
		<g:message code="education.institution.label" default="Sekolah/Institusi" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="institution" value="${educationInstance?.institution}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'yearIn', 'error')} ">
	<label class="col-lg-2 control-label" for="yearIn">
		<g:message code="education.yearIn.label" default="Tahun Masuk" />
		
	</label>
	<div class="col-lg-10"><g:field class="form-control" type="number" name="yearIn" value="${educationInstance.yearIn}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'yearOut', 'error')} ">
	<label class="col-lg-2 control-label" for="yearOut">
		<g:message code="education.yearOut.label" default="Tahun Keluar" />
		
	</label>
	<div class="col-lg-10"><g:field class="form-control" type="number" name="yearOut" value="${educationInstance.yearOut}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'faculty', 'error')} ">
	<label class="col-lg-2 control-label" for="faculty">
		<g:message code="education.faculty.label" default="Fakultas" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="faculty" value="${educationInstance?.faculty}" /></div>

</div>



<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'majors', 'error')} ">
	<label class="col-lg-2 control-label" for="majors">
		<g:message code="education.majors.label" default="Jurusan" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="majors" value="${educationInstance?.majors}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'person', 'error')} " style="display:none;">
	<label class="col-lg-2 control-label" for="person">
		<g:message code="education.person.label" default="Person" />
		
	</label>
	<div class="col-lg-10"><g:select class="form-control" id="person" name="person.id" from="${com.osem.Person.list()}" optionKey="id" required="" value="${educationInstance?.person?.id}"/></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: educationInstance, field: 'title', 'error')} ">
	<label class="col-lg-2 control-label" for="title">
		<g:message code="education.title.label" default="Gelar" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="title" value="${educationInstance?.title}" /></div>

</div>

grails-app/views/education/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'education.label', default: 'Education')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.create.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${educationInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${educationInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:educationInstance, action:'save']"
							class="form-horizontal"
							>
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:submitButton name="create" class="btn btn-primary"
									value="${message(code: 'default.button.create.label', default: 'Create')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/education/edit.gsp
<%@ page import="com.osem.Education" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'education.label', default: 'Education')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.edit.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${educationInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${educationInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:educationInstance, action:'update']"
							method="PUT" class="form-horizontal"
							>
							<g:hiddenField name="version"
								value="${educationInstance?.version}" />
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:actionSubmit class="btn btn-primary" action="update"
									value="${message(code: 'default.button.update.label', default: 'Update')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/education/index.gsp
<%@ page import="com.osem.Education" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'education.label', default: 'Education')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.list.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="bootstrap-admin-panel-content">
						<g:if test="${educationInstanceList}">
							<table class="table bootstrap-admin-table-with-actions">
								<thead>
									<tr>
										
						<g:sortableColumn property="eduLevel" title="${message(code: 'education.eduLevel.label', default: 'Edu Level')}" />
					
						<g:sortableColumn property="faculty" title="${message(code: 'education.faculty.label', default: 'Faculty')}" />
					
						<g:sortableColumn property="institution" title="${message(code: 'education.institution.label', default: 'Institution')}" />
					
						<g:sortableColumn property="majors" title="${message(code: 'education.majors.label', default: 'Majors')}" />
					
						<th><g:message code="education.person.label" default="Person" /></th>
					
						<g:sortableColumn property="title" title="${message(code: 'education.title.label', default: 'Title')}" />
					
									</tr>
								</thead>
								<tbody>
									<g:each in="${educationInstanceList}" status="i"
										var="educationInstance">
										<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
											
						<td><g:link action="show" id="${educationInstance.id}">${fieldValue(bean: educationInstance, field: "eduLevel")}</g:link></td>
					
						<td>${fieldValue(bean: educationInstance, field: "faculty")}</td>
					
						<td>${fieldValue(bean: educationInstance, field: "institution")}</td>
					
						<td>${fieldValue(bean: educationInstance, field: "majors")}</td>
					
						<td>${fieldValue(bean: educationInstance, field: "person")}</td>
					
						<td>${fieldValue(bean: educationInstance, field: "title")}</td>
					
										</tr>
									</g:each>
								</tbody>
							</table>
							<div class="pagination">
								<g:paginate total="${educationInstanceCount ?: 0}" />
							</div>
						</g:if>
						<g:else>
							No education found
						</g:else>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/education/show.gsp
<%@ page import="com.osem.Education" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'education.label', default: 'Education')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.show.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${educationInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${educationInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<dl class="dl-horizontal">
							
				<g:if test="${educationInstance?.eduLevel}">
					<dt><g:message code="education.eduLevel.label" default="Edu Level" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="eduLevel"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.faculty}">
					<dt><g:message code="education.faculty.label" default="Faculty" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="faculty"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.institution}">
					<dt><g:message code="education.institution.label" default="Institution" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="institution"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.majors}">
					<dt><g:message code="education.majors.label" default="Majors" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="majors"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.person}">
					<dt><g:message code="education.person.label" default="Person" /></dt>
					
						<dd><g:link controller="person" action="show" id="${educationInstance?.person?.id}">${educationInstance?.person?.encodeAsHTML()}</g:link></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.title}">
					<dt><g:message code="education.title.label" default="Title" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="title"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.yearIn}">
					<dt><g:message code="education.yearIn.label" default="Year In" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="yearIn"/></dd>
					
				</g:if>
			
				<g:if test="${educationInstance?.yearOut}">
					<dt><g:message code="education.yearOut.label" default="Year Out" /></dt>
					
						<dd><g:fieldValue bean="${educationInstance}" field="yearOut"/></dd>
					
				</g:if>
			
						</dl>
						<g:form url="[resource:educationInstance, action:'delete']"
							method="DELETE">
							<fieldset class="buttons">
								<g:link class="btn btn-primary" action="edit"
									resource="${educationInstance}">
									<g:message code="default.button.edit.label" default="Edit" />
								</g:link>
								<g:actionSubmit class="btn btn-default" action="delete"
									value="${message(code: 'default.button.delete.label', default: 'Delete')}"
									onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>