grails-app/domain/com/osem/WorkHistory.groovy
package com.osem

class WorkHistory {
	
    static belongsTo = [person:Person]
    String workInstitution
    String workAddress
    String workIn
    String workOut
    String workPosition
    Double lastSalary

    static constraints = {
        workAddress nullable:true
        workIn nullable:true
        workOut nullable:true
        workPosition nullable:true
        lastSalary nullable:true
    }
    
    static mapping = {
        person index:true
    }
	
    String toString() {
        workInstitution
    }
}

grails-app/controllers/com/osem/WorkHistoryController.groovy
package com.osem



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_HR'])
@Transactional(readOnly = true)
class WorkHistoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond WorkHistory.list(params), model:[workHistoryInstanceCount: WorkHistory.count()]
    }

    def show(WorkHistory workHistoryInstance) {
        respond workHistoryInstance
    }

    def create() {
        respond new WorkHistory(params)
    }

    @Transactional
    def save(WorkHistory workHistoryInstance) {
        if (workHistoryInstance == null) {
            notFound()
            return
        }

        if (workHistoryInstance.hasErrors()) {
            respond workHistoryInstance.errors, view:'create'
            return
        }

        workHistoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'workHistory.label', default: 'WorkHistory'), workHistoryInstance.id])
                redirect controller:"person",action:"show",id:workHistoryInstance.person.id
            }
            '*' { respond workHistoryInstance, [status: CREATED] }
        }
    }

    def edit(WorkHistory workHistoryInstance) {
        respond workHistoryInstance
    }

    @Transactional
    def update(WorkHistory workHistoryInstance) {
        if (workHistoryInstance == null) {
            notFound()
            return
        }

        if (workHistoryInstance.hasErrors()) {
            respond workHistoryInstance.errors, view:'edit'
            return
        }

        workHistoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'WorkHistory.label', default: 'WorkHistory'), workHistoryInstance.id])
                redirect workHistoryInstance
            }
            '*'{ respond workHistoryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(WorkHistory workHistoryInstance) {

        if (workHistoryInstance == null) {
            notFound()
            return
        }

        workHistoryInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'WorkHistory.label', default: 'WorkHistory'), workHistoryInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'workHistory.label', default: 'WorkHistory'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/workHistory/_form.gsp
<%@ page import="com.osem.WorkHistory" %>


<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'person', 'error')} " style="display: none;">
	<label class="col-lg-2 control-label" for="person">
		<g:message code="workHistory.person.label" default="Person" />
		
	</label>
	<div class="col-lg-10"><g:select class="form-control" id="person" name="person.id" from="${com.osem.Person.list()}" optionKey="id" required="" value="${workHistoryInstance?.person?.id}"/></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'workInstitution', 'error')} ">
	<label class="col-lg-2 control-label" for="workInstitution">
		<g:message code="workHistory.workInstitution.label" default="Nama Perusahaan" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="workInstitution" value="${workHistoryInstance?.workInstitution}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'workAddress', 'error')} ">
	<label class="col-lg-2 control-label" for="workAddress">
		<g:message code="workHistory.workAddress.label" default="Alamat" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="workAddress" value="${workHistoryInstance?.workAddress}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'workPosition', 'error')} ">
	<label class="col-lg-2 control-label" for="workPosition">
		<g:message code="workHistory.workPosition.label" default="Posisi/Jabatan" />
		
	</label>
	<div class="col-lg-10"><g:textField class="form-control" name="workPosition" value="${workHistoryInstance?.workPosition}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'workIn', 'error')} ">
	<label class="col-lg-2 control-label" for="workIn">
		<g:message code="workHistory.workIn.label" default="Tahun Masuk" />
		
	</label>
	<div class="col-lg-10"><g:field type="number" class="form-control" name="workIn" value="${workHistoryInstance?.workIn}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'workOut', 'error')} ">
	<label class="col-lg-2 control-label" for="workOut">
		<g:message code="workHistory.workOut.label" default="Tahun Keluar" />
		
	</label>
	<div class="col-lg-10"><g:field type="number" class="form-control" name="workOut" value="${workHistoryInstance?.workOut}" /></div>

</div>

<div class="form-group fieldcontain ${hasErrors(bean: workHistoryInstance, field: 'lastSalary', 'error')} ">
	<label class="col-lg-2 control-label" for="lastSalary">
		<g:message code="workHistory.lastSalary.label" default="Gaji Terakhir" />
		
	</label>
	<div class="col-lg-10"><g:field class="form-control" type="number" name="lastSalary" value="${workHistoryInstance.lastSalary}" /></div>

</div>

grails-app/views/workHistory/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'workHistory.label', default: 'WorkHistory')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.create.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${workHistoryInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${workHistoryInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:workHistoryInstance, action:'save']"
							class="form-horizontal"
							>
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:submitButton name="create" class="btn btn-primary"
									value="${message(code: 'default.button.create.label', default: 'Create')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/workHistory/edit.gsp
<%@ page import="com.osem.WorkHistory" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'workHistory.label', default: 'WorkHistory')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.edit.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${workHistoryInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${workHistoryInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<g:form url="[resource:workHistoryInstance, action:'update']"
							method="PUT" class="form-horizontal"
							>
							<g:hiddenField name="version"
								value="${workHistoryInstance?.version}" />
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:actionSubmit class="btn btn-primary" action="update"
									value="${message(code: 'default.button.update.label', default: 'Update')}" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>

grails-app/views/workHistory/index.gsp
<%@ page import="com.osem.WorkHistory" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'workHistory.label', default: 'WorkHistory')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.list.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="bootstrap-admin-panel-content">
						<g:if test="${workHistoryInstanceList}">
							<table class="table bootstrap-admin-table-with-actions">
								<thead>
									<tr>
										
						<g:sortableColumn property="lastSalary" title="${message(code: 'workHistory.lastSalary.label', default: 'Last Salary')}" />
					
						<th><g:message code="workHistory.person.label" default="Person" /></th>
					
						<g:sortableColumn property="workAddress" title="${message(code: 'workHistory.workAddress.label', default: 'Work Address')}" />
					
						<g:sortableColumn property="workIn" title="${message(code: 'workHistory.workIn.label', default: 'Work In')}" />
					
						<g:sortableColumn property="workInstitution" title="${message(code: 'workHistory.workInstitution.label', default: 'Work Institution')}" />
					
						<g:sortableColumn property="workOut" title="${message(code: 'workHistory.workOut.label', default: 'Work Out')}" />
					
									</tr>
								</thead>
								<tbody>
									<g:each in="${workHistoryInstanceList}" status="i"
										var="workHistoryInstance">
										<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
											
						<td><g:link action="show" id="${workHistoryInstance.id}">${fieldValue(bean: workHistoryInstance, field: "lastSalary")}</g:link></td>
					
						<td>${fieldValue(bean: workHistoryInstance, field: "person")}</td>
					
						<td>${fieldValue(bean: workHistoryInstance, field: "workAddress")}</td>
					
						<td>${fieldValue(bean: workHistoryInstance, field: "workIn")}</td>
					
						<td>${fieldValue(bean: workHistoryInstance, field: "workInstitution")}</td>
					
						<td>${fieldValue(bean: workHistoryInstance, field: "workOut")}</td>
					
										</tr>
									</g:each>
								</tbody>
							</table>
							<div class="pagination">
								<g:paginate total="${workHistoryInstanceCount ?: 0}" />
							</div>
						</g:if>
						<g:else>
							No workHistory found
						</g:else>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/workHistory/show.gsp
<%@ page import="com.osem.WorkHistory" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'workHistory.label', default: 'WorkHistory')}" />
<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
	<div class="col-md-2 bootstrap-admin-col-left">
		<ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
			<li><g:link action="index">
					<i class="glyphicon glyphicon-list-alt"></i>
					<g:message code="default.list.label" args="[entityName]" />
				</g:link></li>
			<li><g:link action="create">
					<i class="glyphicon glyphicon-plus"></i>
					<g:message code="default.new.label" args="[entityName]" />
				</g:link></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="row">
			<div class="col-lg-12">
				<div class="page-header">
					<h1>
						<g:message code="default.show.label" args="[entityName]" />
					</h1>
				</div>
				<g:if test="${flash.message}">
					<div class="page-body">
						<div class="alert alert-success" role="status">
							<a class="close" data-dismiss="alert" href="#">&times;</a>${flash.message}
						</div>
					</div>
				</g:if>
				<g:hasErrors bean="${workHistoryInstance}">
					<div class="page-body">
						<ul class="alert alert-danger" role="alert">
							<g:eachError bean="${workHistoryInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</div>
				</g:hasErrors>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default bootstrap-admin-no-table-panel">
					<div
						class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
						<dl class="dl-horizontal">
							
				<g:if test="${workHistoryInstance?.lastSalary}">
					<dt><g:message code="workHistory.lastSalary.label" default="Last Salary" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="lastSalary"/></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.person}">
					<dt><g:message code="workHistory.person.label" default="Person" /></dt>
					
						<dd><g:link controller="person" action="show" id="${workHistoryInstance?.person?.id}">${workHistoryInstance?.person?.encodeAsHTML()}</g:link></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.workAddress}">
					<dt><g:message code="workHistory.workAddress.label" default="Work Address" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="workAddress"/></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.workIn}">
					<dt><g:message code="workHistory.workIn.label" default="Work In" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="workIn"/></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.workInstitution}">
					<dt><g:message code="workHistory.workInstitution.label" default="Work Institution" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="workInstitution"/></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.workOut}">
					<dt><g:message code="workHistory.workOut.label" default="Work Out" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="workOut"/></dd>
					
				</g:if>
			
				<g:if test="${workHistoryInstance?.workPosition}">
					<dt><g:message code="workHistory.workPosition.label" default="Work Position" /></dt>
					
						<dd><g:fieldValue bean="${workHistoryInstance}" field="workPosition"/></dd>
					
				</g:if>
			
						</dl>
						<g:form url="[resource:workHistoryInstance, action:'delete']"
							method="DELETE">
							<fieldset class="buttons">
								<g:link class="btn btn-primary" action="edit"
									resource="${workHistoryInstance}">
									<g:message code="default.button.edit.label" default="Edit" />
								</g:link>
								<g:actionSubmit class="btn btn-default" action="delete"
									value="${message(code: 'default.button.delete.label', default: 'Delete')}"
									onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
							</fieldset>
						</g:form>
					</div>
				</div>
			</div>
		</div>

	</div>
</body>
</html>